sudo: false
language: c
compiler:
  - gcc
  - clang
script: s/travis-build
addons:
  apt:
    packages:
      - liblua5.1-dev
      - libtolua-dev
      - libncurses5-dev
      - libsqlite3-dev
      - libxml2-dev
      - valgrind
os:
  - linux
notifications:
  slack:
    secure: F89aXLWaE125PaJIlETv12jT4EfH6wLXJmGCPZzrN3OcLn2ahDWqjwuzR7lOEDf2nAISmeMPyDZMhEHXLNHAE5qP6lg9yliYQw5hzGmDK9m1xUq/pPEne/b2Y7K3my1mkRZ6n3asbHgSmBWAfCIk1JN8R5Rv+rmbLuWLc+zofts=
